name: chart-open-service-broker-azure pipeline
trigger:
  branches:
    include:
    - refs/tags/*
pr:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: cnp-library
    type: github
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'hmcts'

jobs:
- job: Validate
  pool:
    name: hmcts-sandbox-agent-pool
  steps:
  - template: steps/charts/validate.yaml@cnp-library
    parameters :
      chartName: open-service-broker-azure
      chartReleaseName: chart-open-service-broker-azure-ci
      chartNamespace: osba
      helmDeleteWait: "1"
      helmInstallWait: "1"
      helmInstallTimeout: "500"
      serviceConnection: "DCD-CFTAPPS-SBOX"
      aksResourceGroup: "sbox-01-rg"
      aksCluster: "sbox-01-aks"

- job: Release
  # Make sure we have a tag to run this job
  condition: >
    and(
        succeeded(),
        startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      )
  dependsOn: Validate
  pool:
    name: hmcts-sandbox-agent-pool
  steps:
  - template: steps/charts/release.yaml@cnp-library
    parameters:
      chartName: open-service-broker-azure
      chartReleaseName: chart-open-service-broker-azure
      chartNamespace: osba
      serviceConnection: "DCD-CFTAPPS-SBOX"
      aksResourceGroup: "sbox-01-rg"
      aksCluster: "sbox-01-aks"
